### ISSUE TITLE
Use svelte kit instead sapper.

### ISSUE THREAD

**Issue by jechaviz** [jhipster/jhipster-sample-app-svelte#3]
As announced by Svelte author Sapper won't be upgraded, and now he is advising the use of the svelte kit. 

https://kit.svelte.dev
https://kit.svelte.dev/migrating

It's announced the migration Svelte kit, is smooth. So it must not suppose a big change in your blueprint. Thank you.

**Comment by vishal423** [comment]
Thanks for raising the issue. It's already been tracked via https://github.com/jhipster/generator-jhipster-svelte/issues/46
